# Generated by Django 4.2.13 on 2024-06-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_chatid_user_userpicture_conversations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatid",
            old_name="chatId",
            new_name="chatid",
        ),
        migrations.RenameField(
            model_name="conversations",
            old_name="conversationId",
            new_name="conversationid",
        ),
    ]
