# Generated by Django 4.2.13 on 2024-06-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_chatid_chatid_chatid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversations",
            name="chatid",
        ),
        migrations.RemoveField(
            model_name="conversations",
            name="userid",
        ),
        migrations.DeleteModel(
            name="Chatid",
        ),
        migrations.DeleteModel(
            name="Conversations",
        ),
    ]
