# Generated by Django 4.2.13 on 2024-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_conversations_chatid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Name of User"
            ),
        ),
    ]
