# Generated by Django 4.2.13 on 2024-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.TextField(
                blank=True, max_length=25, null=True, verbose_name="Name of User"
            ),
        ),
    ]
