# Generated by Django 4.2.13 on 2024-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currentchatid",
            field=models.CharField(blank=True, default="", null=True),
        ),
    ]
