# Generated by Django 4.2.13 on 2024-06-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_currentchatid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currentchatid",
            field=models.CharField(blank=True, default=""),
        ),
    ]
