version: '3.7'

volumes:
  llm_on_web_local_postgres_data: {}
  llm_on_web_local_postgres_data_backups: {}
  llm_on_web_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: llm_on_web_local_django
    container_name: llm_on_web_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - .env
    ports:
      - '8091:8000'
    extra_hosts:
       - "host.docker.internal:host-gateway"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: llm_on_web_production_postgres
    container_name: llm_on_web_local_postgres
    volumes:
      - llm_on_web_local_postgres_data:/var/lib/postgresql/data
      - llm_on_web_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: llm_on_web_local_redis
    volumes:
      - llm_on_web_local_redis_data:/data

  celeryworker:
    <<: *django
    image: llm_on_web_local_celeryworker
    container_name: llm_on_web_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: llm_on_web_local_celerybeat
    container_name: llm_on_web_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: llm_on_web_local_flower
    container_name: llm_on_web_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
