volumes:
  llm_on_web_local_postgres_data: {}
  llm_on_web_local_postgres_data_backups: {}
  llm_on_web_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: llm_on_web_local_django
    container_name: llm_on_web_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - .env
    ports:
      - '8091:8000'
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: llm_on_web_production_postgres
    container_name: llm_on_web_local_postgres
    volumes:
      - llm_on_web_local_postgres_data:/var/lib/postgresql/data
      - llm_on_web_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres


  redis:
    image: docker.io/redis:6
    container_name: llm_on_web_local_redis

    volumes:
      - llm_on_web_local_redis_data:/data
