# Generated by Django 4.2.13 on 2024-06-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversations",
            name="imagequery",
            field=models.ImageField(
                blank=True, null=True, upload_to="user-images-query/"
            ),
        ),
        migrations.AlterField(
            model_name="conversations",
            name="llm_response",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
