# Generated by Django 4.2.13 on 2024-06-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversations_imagequery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversations",
            name="llm_response",
            field=models.TextField(blank=True, default=""),
        ),
    ]
