# Generated by Django 4.2.13 on 2024-06-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatid_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatid",
            name="chat_title",
            field=models.CharField(blank=True, default=""),
        ),
    ]
