# Generated by Django 4.2.13 on 2024-07-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatid_chat_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatid",
            name="chat_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conversations",
            name="llm_response",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
